"""add_handler_role_and_user_fields

Revision ID: 159a048b5c17
Revises: d358706479f9
Create Date: 2025-10-26 01:14:50.927101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159a048b5c17'
down_revision = 'd358706479f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('dog_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'dog', ['dog_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dog_id')
        batch_op.drop_column('project_id')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
