"""add_backup_settings_table

Revision ID: 5a793c6878a3
Revises: 5a09bed29e63
Create Date: 2025-10-13 16:51:10.833780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a793c6878a3'
down_revision = '5a09bed29e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('backup_frequency', sa.Enum('DISABLED', 'DAILY', 'WEEKLY', 'MONTHLY', name='backupfrequency'), nullable=False),
    sa.Column('backup_hour', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('google_drive_enabled', sa.Boolean(), nullable=False),
    sa.Column('google_drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('google_drive_credentials', sa.Text(), nullable=True),
    sa.Column('last_backup_at', sa.DateTime(), nullable=True),
    sa.Column('last_backup_status', sa.String(length=50), nullable=True),
    sa.Column('last_backup_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deworming_log', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deworming_log', schema=None) as batch_op:
        batch_op.alter_column('project_id',
               existing_type=sa.UUID(),
               nullable=False)

    op.drop_table('backup_settings')
    # ### end Alembic commands ###
